.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. kindcoin_qt test_kindcoin_qt
clean: FORCE
	$(MAKE) -C .. kindcoin_qt_clean test_kindcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_kindcoin_qt_check
kindcoin-qt kindcoin-qt.exe: FORCE
	 $(MAKE) -C .. kindcoin_qt
